### ISSUE TITLE
Room情報の取得

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-admin#103]
## やること
Room情報の取得

## 作る場所
feature/room/api/getRoom

## Swagger
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/lit-kansai/dj_system-api/main/public/docs/dj-system-api.yaml#/%2Fmc%2Froom/get_mc_room__roomId_

**Comment by penguin4731** [comment]
https://github.com/lit-kansai/dj-system-admin/issues/97
これと同じ？

**Comment by txxxxc** [comment]
これと同じです🙏
