### ISSUE TITLE
ルームに連携されているプレイリストの楽曲一覧を取得

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-admin#108]
## やること
ルームに連携されているプレイリストの楽曲一覧を取得のAPIを呼び出す関数を作る

## 作る場所
feature/playlist/api/getPlaylist

## Swagger
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/lit-kansai/dj_system-api/main/public/docs/dj-system-api.yaml

**Comment by penguin4731** [comment]
使わなさそうなので、Close
