### ISSUE TITLE
ルーム概要のUI構築

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-admin#20]
ルーム概要のUI構築お願いします！

## 参考画像
![image](https://user-images.githubusercontent.com/22112440/201806525-069bf70d-9978-499a-a867-e931b521453f.png)

## 該当するFigmaのURL
https://www.figma.com/file/ARpMulqQgkx4kdPyFvgde1/DJ-team-library?node-id=414%3A2571&t=chDfzOlkyoHyTHK6-0

**Comment by kuro48** [comment]
共有URLとプレイリストの部分の画像ってもらえたりします？それとも既にどこかに入ってます？

**Comment by txxxxc** [comment]
a
